### ISSUE TITLE
cs2-map-importer. gameinfo.txt not found

### ISSUE THREAD

**Issue by Pureple13** [sarim-hk/cs2-map-importer#3]
Hi ! First, i'm pretty much newbie in that but watching all tutos and reading the devs documentation, I'm not able to import my maps from csgo. I did all the prerequisites, I pretty much understand what has to be done but the gameinfo.txt from source 1 is missing from G:\Steam\steamapps\common\Counter-Strike Global Offensive\csgo. I don't know if they removed it or just moved it but can't find it. It was there a month ago, I think all this is from the fact that they don't want us to play csgo anymore. Any ideas where they moved it ? (I tried using the gameinfo.gi by copy/pasting it in gameinfo.txt from csgo_core, csgo_imported, csgo_lv,csgo (that is source 2 in reality). Nothing is working.

**Comment by sarim-hk** [comment]
Hi,
You must download the CS:GO Legacy beta branch on steam. You can right click CS2 then select properties, then betas. There will be the option you're looking for here.
