### ISSUE TITLE
Failed to load file (invalid)! Looking for pak01.vpk

### ISSUE THREAD

**Issue by VincentW2** [sarim-hk/cs2-map-importer#5]
Hello, 
I tried importing a map, but it seems the program is looking for a file that doesn't exist.
![image](https://github.com/sarim-hk/cs2-map-importer/assets/17298607/62f54b3e-219d-4733-acfd-dd7c04622c48)
I have cs added to path, and the csgo legacy branch downloaded, and all of my map matierals etc added to the correct folder, but I am not sure why its looking for the pak01 vpk. I don't have a pak01 vpk in the csgo folder, I only have a pak01-000.vpk.

Thank you.

**Comment by sarim-hk** [comment]
Ah right, this is due to a recent bug since a new update. You need to rename the file "vpk.signatures" to anything else, ("vpk.signatures.old" for example). The file is in Counter-Strike Global Offensive\game\bin\win64, I'll make an amendment to the README for that.

**Comment by VincentW2** [comment]
> Ah right, this is due to a recent bug since a new update. You need to rename the file "vpk.signatures" to anything else, ("vpk.signatures.old" for example). The file is in Counter-Strike Global Offensive\game\bin\win64, I'll make an amendment to the README for that.

Thanks, that worked. Seems like it works but i get one final error:
![image](https://github.com/sarim-hk/cs2-map-importer/assets/17298607/f9d5983b-de64-4b82-9923-32da11797ffb)

I looked up the error and it seems others have had this issue by recompiling with the older hammer? Is there a way you were able to fix this?

**Comment by sarim-hk** [comment]
This is because it's a decompiled map. You have to open it in source 1 hammer, save it, then it should work fine. Nothing I can fix on my end here.

**Comment by VincentW2** [comment]
> This is because it's a decompiled map. You have to open it in source 1 hammer, save it, then it should work fine. Nothing I can fix on my end here.

Appriciate it, thanks.
