### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Alltroo** [sarim-hk/cs2-map-importer#7]
CVMFtoVMAP: Missing a required top-level key.
Failed to construct map document from provided vmf data.
source1import - Encountered an error importing file "c:\users\alex\appdata\local\temp\maps\frypemap_v8_d_d.vmf"!
        *** Error Importing c:\users\alex\appdata\local\temp\maps\frypemap_v8_d_d.vmf

-----------------------------------------------------------------
FAILED:
 c:\users\alex\appdata\local\temp\maps\frypemap_v8_d_d.vmf
-----------------------------------------------------------------

-----------------------------------------------------------------
 ERROR: 0 imported, 1 failed, 0 skipped, 0 unknown, 0m:01s
-----------------------------------------------------------------
Error running:
>>>source1import -retail -nop4 -nop4sync -usebsp -src1gameinfodir "D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo" -src1contentdir "C:\Users\Alex\AppData\Local\Temp" -s2addon "vvv" -game csgo maps\frypemap_v8_d_d.vmf
Aborting

**Comment by sarim-hk** [comment]
save the map in source 1 hammer once before you port

**Comment by Alltroo** [comment]
And where will be the imported map in CS2 menu?

**Comment by sarim-hk** [comment]
watch the attached tutorial video

**Comment by Alltroo** [comment]
![image](https://github.com/user-attachments/assets/a1149df9-b01c-4e3f-adb2-642678e21412)
I did like in a video

**Comment by Alltroo** [comment]
[cs2importer_log.txt](https://github.com/user-attachments/files/18252589/cs2importer_log.txt)
And this is my log from importer console (there's no any text like "Succesfully imported" like in the video).

> save the map in source 1 hammer once before you port

**Comment by Alltroo** [comment]
How to fix this?

**Comment by sarim-hk** [comment]
looks like you just didn't let it finish

**Comment by Alltroo** [comment]
> looks like you just didn't let it finish

How many time it usually takes?

**Comment by sarim-hk** [comment]
like 10 mins tops and make sure you don't have anything selected in the cmd window otherwise it will block it from running

**Comment by Alltroo** [comment]
![image](https://github.com/user-attachments/assets/add465b9-f4f4-44b7-bc84-41fb435ba3e0)
What is this?

**Comment by Alltroo** [comment]
And process stopped. How to fix this?

**Comment by Alltroo** [comment]
> And process stopped.

**Comment by sarim-hk** [comment]
I don't know. Please stop flooding my emails, this is an issue with the importer tool on valves end not mine
